[package]
name = "mecha-usb"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Dhruvesh08/mecha-usb"
homepage = "https://github.com/Dhruvesh08/mecha-usb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
